#check package-lock file version

name: Lockfile Version check

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  version-check:
    runs-on:  ubuntu-20.04
    env:
      VERSION: '0'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Retrieve version
      id: getversion
      run: |
        cat package-lock.json | grep '\"lockfileVersion\": 2,' > ${{ VERSION }};
        echo "$VERSION";
    - name: check value
      if: ${{ env.VERSION == null }}
      run: |
        echo "ERROR: Outdated package-lock file. Use NPM8 to install dependencies ";
        exit 1
